name: release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag: git tag"
        required: true

env:
  GIT_TAG: ${{ github.event.inputs.tag }}


jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
      - run: dotnet build src/Simple.Dotnet.Utilities -c Release -p:Version=${{ env.GIT_TAG }}
      - run: dotnet test src/Simple.Dotnet.Utilities.Tests -c Release --no-build
      - run: dotnet pack src/Simple.Dotnet.Utilities/Simple.Dotnet.Utilities.csproj -c Release --no-build -p:Version=${{ env.GIT_TAG }} -o ./publish
      - uses: actions/upload-artifact@v1
        with:
          name: nuget
          path: ./publish/
          retention-days: 1

  publish-artifact:
    needs: [build-dotnet]
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
      - uses: actions/download-artifact@v2-preview
      - run: dotnet nuget push "*.nupkg" --skip-duplicate -s https://www.nuget.org/api/v2/package -k ${{ secrets.NUGET_KEY }}